/* Exception handlers
   First parameter: exception code */

EXC (0)
EXC (1)
EXC (2)
EXC (3)
EXC (4)
EXC (5)
EXC (6)
EXC (7)
EXC (8)
EXC (10)
EXC (11)
EXC (12)
EXC (13)
EXC (14)
EXC (16)
EXC (17)
EXC (18)
EXC (19)
EXC (20)
EXC (30)

/* Interrupt handlers
   First parameter: IRQ number */

IRQ (0)
IRQ (1)
IRQ (2)
IRQ (3)
IRQ (4)
IRQ (5)
IRQ (6)
IRQ (7)
#ifndef IRQ_SKIP_8
IRQ (8)
#endif
IRQ (9)
IRQ (10)
IRQ (11)
IRQ (12)
IRQ (13)
IRQ (14)
IRQ (15)
